/**
 * Crisis outlines: one simplified boundary per crisis, generated by
 * scripts/build-outlines.py into public/geo/outlines.json and fetched once
 * on demand so the globe bundle stays free of geometry.
 */
import { GLOBE_RADIUS, ORBITAL_DISTANCE, ORBITAL_FOV, ZOOM_MIN } from "./constants";

export interface Outline {
  /** Closed rings of [longitude, latitude] pairs. */
  rings: [number, number][][];
  /** Angular distance in degrees from the marker to the outline's far edge. */
  extent: number;
  /** True for a drawn circle around a loose area with no agreed boundary. */
  approximate?: boolean;
}

export type Outlines = Record<string, Outline>;

let request: Promise<Outlines> | null = null;

export function loadOutlines(): Promise<Outlines> {
  if (!request) {
    request = fetch("/geo/outlines.json").then((response) => {
      if (!response.ok) throw new Error(`outlines ${response.status}`);
      return response.json() as Promise<Outlines>;
    });
    request.catch(() => {
      request = null;
    });
  }
  return request;
}

/** Outline height as a share of the frame once the camera has closed in. */
const FIT_SHARE = 0.72;

/**
 * Camera distance at which an outline of the given angular extent fills
 * FIT_SHARE of the frame. `frameShare` is the frame's height as a fraction
 * of the canvas height: 1 when the canvas is the frame, less when the globe
 * is drawn on a canvas larger than the window it shows through.
 */
export function fitDistance(extentDegrees: number, frameShare = 1): number {
  const a = (extentDegrees * Math.PI) / 180;
  const halfFov = (ORBITAL_FOV * Math.PI) / 360;
  const distance =
    GLOBE_RADIUS * Math.cos(a) +
    (GLOBE_RADIUS * Math.sin(a)) /
      (FIT_SHARE * frameShare * Math.tan(halfFov));
  return Math.min(ORBITAL_DISTANCE, Math.max(ZOOM_MIN, distance));
}
